<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>WinOverlay</AssemblyName>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <OutputPath>..\Assets\StreamingAssets\WinOverlay\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.27.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.IO.Pipes" Version="4.3.0" />
    <PackageReference Include="System.IO.MemoryMappedFiles" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="WinOverlay\Converter\" />
  </ItemGroup>

  <!--<ItemGroup>
    <Folder Include="WinOverlay\Generated\" />
  </ItemGroup>-->

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="xcopy &quot;$(ProjectDir)ShareScript\*&quot; &quot;$(ProjectDir)..\Assets\Scripts\ShareScript\&quot; /Y /I /E" />
    <Exec Command="cmd /c &quot;$(ProjectDir)WinOverlay\generate.bat&quot;" WorkingDirectory="$(ProjectDir)WinOverlay" />
  </Target>

</Project>