<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
  <OutputType>WinExe</OutputType>
  <TargetFramework>net8.0-windows</TargetFramework>
  <UseWPF>true</UseWPF>
  <Nullable>disable</Nullable>
  <RootNamespace>WinOverlayV2</RootNamespace>
  <AssemblyName>WinOverlayV2</AssemblyName>
  <StartupObject>WinOverlayV2.App</StartupObject>
</PropertyGroup>

<PropertyGroup Condition="'$(Configuration)' == 'Release'">
  <!--<OutputPath>.\Build\StreamingAssets\WinOverlay\</OutputPath>-->
  <OutputPath>..\Assets\StreamingAssets\WinOverlay\</OutputPath>
  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
