syntax = "proto3";

option csharp_namespace = "WinOverlay";

package DesktopWizard.Events;

message PointP3 {
    int32 x = 1;
    int32 y = 2;
}

message MouseEventP3 {
    int32 button = 1;
    int32 clicks = 2;
    int32 x = 3;
    int32 y = 4;
    int32 delta = 5;
    PointP3 location = 6;
}

message KeyboardEventP3 {
    int32 keyData = 1;
    int32 keyCode = 2;
    bool alt = 3;
    bool control = 4;
    bool shift = 5;
    bool handled = 6;
    bool suppressKeyPress = 7;
    bool isKeyUp = 8;
}
