syntax = "proto3";
option csharp_namespace = "Share";
package DesktopWizard.Events;
message Vec2 {
    float x = 1;
    float y = 2;
}
message Vec2Int {
    int32 x = 1;
    int32 y = 2;
}
message Vec3 {
    float x = 1;
    float y = 2;
    float z = 3;
}
message Mat4x4
{
    repeated float m = 1; // 16 float values for a 4x4 matrix
}
message MouseEventP3 {
    int32 button = 1;
    int32 clicks = 2;
    int32 x = 3;
    int32 y = 4;
    int32 delta = 5;
}
message KeyboardEventP3 {
    int32 keyCode = 1;
    bool alt = 2;
    bool control = 3;
    bool shift = 4;
    bool handled = 6;
    bool suppressKeyPress = 7;
    bool isKeyUp = 8;
}
