using System;
using System.Collections;
using System.Collections.Generic;
namespace Gaia
{
	[System.Serializable]
	public class GxMotionData : IEqualityComparer<GxMotionData>
    {
		public GxMotionKey Key;

		/// VRMA case.
		/// VRMA can only locate in the VRM folder, which is defined in <see cref="GxConst.Path.VRM"/>.
		/// 
		/// Timeline case.
		/// Timeline are addressable assets, which can be located in addressable panel.
		/// all timelines should generated by <see cref="GxGenerateClip"/> and cache record in <see cref="GxTimelineCollection"/>
		/// the play method is <see cref="GxCharacter.CrossFade"/>
		public eAssetType Type => Key.Type;

		/// addressable path or VRMA path
		public string Path => Key.Path;
		
		// length of the animation clip, seconds
		public float ClipLength;

		// is this animation looped?
		public bool IsLoop;

		public eEmotion Emotion;
		public float Weight = 1.0f;
		// public float BlinkSuppression = 1.0f;
		// TODO: Optional fields
		//public List<string> Tags = new();
		//public int Priority = 0;
		//public float BodyMotionIntensity = 1.0f;
		//public bool FacialBlendOverride = false;
		//public bool UseMouthMotion = false;

		/// <summary>
		/// Generate via script
		/// </summary>
		/// <param name="isVRMA"></param>
		/// <param name="path"></param>
		/// <returns></returns>
		public static GxMotionData Create(eAssetType type, string path, float clipLength, bool isLoop)
		{
			return new GxMotionData
			{
				Key = new GxMotionKey(path, type),
				ClipLength = clipLength,	
				IsLoop = isLoop,
			};
		}

		public void AddNext(string nextPath, eAssetType nextType)
		{
			var next = new GxMotionKey(nextPath, nextType);
			AddNext(next);
		}

		public void AddNext(GxMotionKey next)
		{
			if (next.Type != Type)
			{
				throw new ArgumentException($"Cannot add motion of different type: {next.Type} to {Type}");
			}
			if (string.IsNullOrEmpty(next.Path))
			{
				throw new ArgumentException($"Cannot add empty path: {next.Path} to {Path}");
			}
			if (!next.Valid)
			{
				throw new Exception($"Cannot add invalid motion: {next} to {this}");
			}
		}

		public bool Equals(GxMotionData x, GxMotionData y)
		{
			return x.Path == y.Path && x.Type == y.Type;
		}

		public int GetHashCode(GxMotionData obj)
		{
			return HashCode.Combine(obj.Path, Type);
		}

		public override string ToString()
		{
			return $"Motion:{Type}, Len:{ClipLength},{(IsLoop?"Loop":"")} {Path}";
		}
	}
}