using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace Gaia
{
	/// <summary>
	/// In order to convert into <see cref="GxMotionData"/>
	/// for easy modify within development stage.
	/// </summary>
	public abstract class GxMotionData_BuildinDraft : ScriptableObject { }


	[System.Serializable]
	public class GxMotionData : IEqualityComparer<GxMotionData>
    {
		public GxMotionKey Key;

		/// VRMA case.
		/// VRMA can only locate in the VRM folder, which is defined in <see cref="GxConst.Path.VRM"/>.
		/// 
		/// Timeline case.
		/// Timeline are addressable assets, which can be located in addressable panel.
		/// all timelines should generated by <see cref="GxGenerateClip"/> and cache record in <see cref="GxTimelineCollection"/>
		/// the play method is <see cref="GxCharacter.CrossFade"/>
		public eAssetType Type => Key.Type;

		/// addressable path or VRMA path
		public string Path => Key.Path;
		
		// length of the animation clip, seconds
		public float ClipLength;

		// is this animation looped?
		public bool IsLoop;

		// public eEmotion Emotion;
		public float Weight = 1.0f;
		// public float BlinkSuppression = 1.0f;
		// TODO: Optional fields
		//public List<string> Tags = new();
		//public int Priority = 0;
		//public float BodyMotionIntensity = 1.0f;
		//public bool FacialBlendOverride = false;
		//public bool UseMouthMotion = false;
		
		[SerializeField] List<string> m_Tags;
		public List<string> Tags
		{
			get
			{
				if (m_Tags == null)
				{
					m_Tags = new List<string>();
				}
				return m_Tags;
			}
			private set
			{
				m_Tags = value;
			}
		}
		public void SetTags(IList<string> tags)
		{
			this.Tags = new List<string>(tags);
		}

		public int ContainTags(params string[] tags)
		{
			var match = 0;
			if (tags.Length == 1 && string.IsNullOrEmpty(tags[0]))
			{
				// special handle contain "empty" cases, it match ANY pose.
				return 1;
			}

			foreach (var tag in tags)
			{
				if (string.IsNullOrEmpty(tag))
					continue;
				var val = tag?.Trim().ToLowerInvariant();
				if (Tags.Contains(val))
					++match;
			}
			return match;
		}

		/// <summary>
		/// Generate via script
		/// </summary>
		/// <param name="isVRMA"></param>
		/// <param name="path"></param>
		/// <returns></returns>
		public static GxMotionData Create(eAssetType type, string path, float clipLength, bool isLoop)
		{
			return new GxMotionData
			{
				Key = new GxMotionKey(path, type),
				ClipLength = clipLength,	
				IsLoop = isLoop,
			};
		}

		public bool Equals(GxMotionData x, GxMotionData y)
		{
			return x.Path == y.Path && x.Type == y.Type;
		}

		public int GetHashCode(GxMotionData obj)
		{
			return HashCode.Combine(obj.Path, Type);
		}

		public override string ToString()
		{
			return $"Motion:{Type}, Len:{ClipLength},{(IsLoop?"Loop":"")} {Path}";
		}
	}
}