using Kit2;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
namespace Gaia
{
	public enum eEmotion : int
	{
		Unknown = 0,
		Neutral,
		Happy,
		Sadness,
		Anger,
		Frightened,
		Speechless,
		Sleep,
	}

	public enum eAssetType : int
	{
		Unknown = 0,
		VRMA, // VRM Animation
		Timeline, // Timeline Animation
	}

	[System.Serializable]
	public class GxMotionData : IEqualityComparer<GxMotionData>
    {
		/// addressable path or VRMA path
		public string Path;

		/// VRMA case.
		/// VRMA can only locate in the VRM folder, which is defined in <see cref="GxConst.Path.VRM"/>.
		/// and play by method. <see cref="GxCharacter.CrossFadeVRMA(string)"/>
		/// 
		/// Timeline case.
		/// Timeline are addressable assets, which can be located in addressable panel.
		/// all timelines should generated by <see cref="GxGenerateClip"/> and cache record in <see cref="GxTimelineCollection"/>
		/// the play method is <see cref="GxCharacter.CrossFade(string, float, Kit2.ObjectPool.eSrcType, bool)"/>
		[JsonIgnore]
		public eAssetType Type;
		
		// length of the animation clip, seconds
		public float ClipLength;

		// is this animation looped?
		public bool IsLoop;


		// TODO: more information
		[JsonIgnore]
		public eEmotion Emotion;
		public float Weight = 1.0f;
		// public float BlinkSuppression = 1.0f;
		// TODO: Optional fields
		//public List<string> Tags = new();
		//public int Priority = 0;
		//public float BodyMotionIntensity = 1.0f;
		//public bool FacialBlendOverride = false;
		//public bool UseMouthMotion = false;

		/// <summary>
		/// Generate via script
		/// </summary>
		/// <param name="isVRMA"></param>
		/// <param name="path"></param>
		/// <returns></returns>
		public static GxMotionData Create(eAssetType type, string path, float clipLength, bool isLoop)
		{
			return new GxMotionData
			{
				Path = path,
				Type = type,
				ClipLength = clipLength,	
				IsLoop = isLoop,
			};
		}

		public bool Equals(GxMotionData x, GxMotionData y)
		{
			return x.Path == y.Path && x.Type == y.Type;
		}

		public int GetHashCode(GxMotionData obj)
		{
			return HashCode.Combine(obj.Path, Type);
		}

		public override string ToString()
		{
			return $"Motion:{Type}, Len:{ClipLength},{(IsLoop?"Loop":"")} {Path}";
		}
	}
}